extension PlayerLocalization {
    public static let russian = PlayerLocalization(
        playbackSpeed: "Скорость",
        audio: "Аудио",
        subtitles: "Субтитры",
        subtitleSize: "Размер субтитров",
        playbackStats: "Статистика",
        hideStats: "Скрыть статистику",
        liveIndicator: "LIVE",
        goLive: "В эфир",
        done: "Готово",
        off: "Выкл",
        searchOnlineSubtitles: "Поиск субтитров",
        removeExternalSubtitles: "Убрать внешние",
        externalSubtitleActive: "Внешние субтитры",
        volumeBoost: "Усиление звука",
        upNext: "Далее",
        watchAgain: "Смотреть снова",
        statsVideo: "ВИДЕО",
        statsAudioSubs: "АУДИО / СУБТИТРЫ",
        statsNetwork: "СЕТЬ",
        statsResolution: "Разрешение",
        statsVideoCodec: "Видеокодек",
        statsFrameRate: "Частота кадров",
        statsPlaybackRate: "Скорость воспр.",
        statsDroppedFrames: "Пропущ. кадры",
        statsAudioCodec: "Аудиокодек",
        statsAudioTrack: "Аудиодорожка",
        statsSubtitle: "Субтитры",
        statsAvgBitrate: "Сред. битрейт",
        statsCurBitrate: "Тек. битрейт",
        statsObservedBR: "Наблюд. битрейт",
        statsThroughput: "Пропускн. спос.",
        statsBuffer: "Буфер",
        statsStalls: "Задержки",
        statsNetworkType: "Тип сети",
        statsStreamType: "Тип потока",
        statsSource: "Источник"
    )
}
